import Head from "next/head"
import WalletConnectProvider from "@walletconnect/web3-provider"
import { providers, ethers } from "ethers"

var address = "0xe138921836cA7A88CBd99Ab280a64f51563691b7"
var abi = [
  {
    inputs: [{ internalType: "uint256", name: "count_", type: "uint256" }],
    name: "add",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "count",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
]

export default function Ethers() {
  let web3Provider
  const provider = new WalletConnectProvider({
    infuraId: "461d35d8280c4ee78f25da15fdcc48c1",
  })

  const connect = async () => {
    const instance = await provider.enable()
    web3Provider = new providers.Web3Provider(provider).getSigner()
    console.log("connected")
  }

  const disConnect = async () => {
    await provider.disconnect()
  }

  const count = async () => {
    console.log(web3Provider)
    // new ethers.ContractFactory(abi, address, web3Provider)
    const contract = new ethers.Contract(abi, address, web3Provider)
    const count = await contract.count()
    console.log(count)
  }

  return (
    <div>
      <Head>
        <title>Wallet Connect</title>
        <meta name="description" content="Generated by Wallet Connect" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={connect}>connect</button>
        <button onClick={disConnect}>disConnect</button>
        <button onClick={count}>count</button>
      </main>
    </div>
  )
}
