import Head from "next/head"
import WalletConnectProvider from "@walletconnect/web3-provider"
import Web3 from "web3"

var address = "0xe138921836cA7A88CBd99Ab280a64f51563691b7"

var abi = [
  {
    inputs: [{ internalType: "uint256", name: "count_", type: "uint256" }],
    name: "add",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "count",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
]

export default function Web3() {
  let web3
  let contract
  const provider = new WalletConnectProvider({
    infuraId: "461d35d8280c4ee78f25da15fdcc48c1",
  })

  const connect = async () => {
    await provider.enable()
    web3 = new Web3(provider)
    contract = new web3.eth.Contract(abi, address)
    console.log("connected")
  }

  const disConnect = async () => {
    await provider.disconnect()
  }

  const count = async () => {
    const count = await contract.methods.count().call()
    console.log(count)
  }

  return (
    <div>
      <Head>
        <title>Wallet Connect</title>
        <meta name="description" content="Generated by Wallet Connect" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={connect}>connect</button>
        <button onClick={disConnect}>disConnect</button>
        <button onClick={count}>count</button>
      </main>
    </div>
  )
}
